name: devops app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Run tests
        run: |
          pytest
 
      - name: List Files
        run: |
          echo "Len a genius"
  deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Checkout branch
            uses: actions/checkout@v4
    
          - name: Docker Login
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Docker Build and Push
            # This step builds the Docker image and pushes it to the Docker registry
            run: |
              echo "Building and pushing Docker image..."
              docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }} .
              docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
          - name: Deploy to Server
            # This step deploys the Docker image to the server
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'devopsepita'
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              images: ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
 